"""
Topic 04: Two Pointers & Sliding Window
"""

from ..types import TestCasesDict

TOPIC_04_TESTS: TestCasesDict = {
    "valid_palindrome": [
        {
            "args": ["A man, a plan, a canal: Panama"],
            "expected": True,
            "name": "classic palindrome",
        },
        {"args": ["race a car"], "expected": False, "name": "not palindrome"},
        {"args": [" "], "expected": True, "name": "space only"},
        {"args": [""], "expected": True, "name": "empty string"},
        {"args": ["a"], "expected": True, "name": "single char"},
        {"args": ["ab"], "expected": False, "name": "two different chars"},
        {"args": ["aa"], "expected": True, "name": "two same chars"},
        {"args": ["0P"], "expected": False, "name": "alphanumeric"},
    ],
    "two_sum_sorted": [
        {"args": [[2, 7, 11, 15], 9], "expected": [1, 2], "name": "basic case"},
        {"args": [[2, 3, 4], 6], "expected": [1, 3], "name": "skip middle"},
        {"args": [[1, 2], 3], "expected": [1, 2], "name": "two elements"},
        {"args": [[-1, 0], -1], "expected": [1, 2], "name": "with negative"},
        {"args": [[1, 2, 3, 4, 5], 9], "expected": [4, 5], "name": "at end"},
        {"args": [[1, 2, 3, 4, 5], 3], "expected": [1, 2], "name": "at start"},
        {
            "args": [[1, 1, 2, 3], 2],
            "expected": [1, 1],
            "name": "duplicate values as answer",
        },
    ],
    "three_sum": [
        {
            "args": [[-1, 0, 1, 2, -1, -4]],
            "expected": [[-1, -1, 2], [-1, 0, 1]],
            "name": "basic triplets",
            "compare": "set_of_tuples",
        },
        {"args": [[0, 1, 1]], "expected": [], "name": "no triplet"},
        {
            "args": [[0, 0, 0]],
            "expected": [[0, 0, 0]],
            "name": "all zeros",
            "compare": "set_of_tuples",
        },
        {"args": [[]], "expected": [], "name": "empty array"},
        {"args": [[0]], "expected": [], "name": "single element"},
        {
            "args": [[-2, 0, 1, 1, 2]],
            "expected": [[-2, 0, 2], [-2, 1, 1]],
            "name": "multiple triplets",
            "compare": "set_of_tuples",
        },
    ],
    "container_with_most_water": [
        {"args": [[1, 8, 6, 2, 5, 4, 8, 3, 7]], "expected": 49, "name": "basic case"},
        {"args": [[1, 1]], "expected": 1, "name": "two elements"},
        {"args": [[4, 3, 2, 1, 4]], "expected": 16, "name": "same height ends"},
        {"args": [[1, 2, 1]], "expected": 2, "name": "three elements"},
        {"args": [[2, 3, 4, 5, 18, 17, 6]], "expected": 17, "name": "tall in middle"},
        {"args": [[5, 5, 5, 5]], "expected": 15, "name": "all equal heights"},
        {"args": [[0, 0]], "expected": 0, "name": "zero heights"},
    ],
    "max_sum_subarray_k": [
        {
            "args": [[1, 4, 2, 10, 23, 3, 1, 0, 20], 4],
            "expected": 39,
            "name": "basic window",
        },
        {"args": [[1, 2, 3], 3], "expected": 6, "name": "window equals length"},
        {"args": [[5], 1], "expected": 5, "name": "single element"},
        {"args": [[1, 2, 3, 4, 5], 2], "expected": 9, "name": "window at end"},
        {"args": [[-1, -2, -3, -4], 2], "expected": -3, "name": "all negative"},
        {
            "args": [[-1, 4, -2, 5, 3], 3],
            "expected": 7,
            "name": "mixed positive negative",
        },
    ],
    "longest_substring_without_repeating": [
        {"args": ["abcabcbb"], "expected": 3, "name": "basic case"},
        {"args": ["bbbbb"], "expected": 1, "name": "all same"},
        {"args": ["pwwkew"], "expected": 3, "name": "middle substring"},
        {"args": [""], "expected": 0, "name": "empty string"},
        {"args": [" "], "expected": 1, "name": "single space"},
        {"args": ["au"], "expected": 2, "name": "two different"},
        {"args": ["dvdf"], "expected": 3, "name": "overlapping"},
    ],
    "remove_duplicates_sorted": [
        {"args": [[1, 1, 2]], "expected": 2, "name": "basic case"},
        {
            "args": [[0, 0, 1, 1, 1, 2, 2, 3, 3, 4]],
            "expected": 5,
            "name": "multiple duplicates",
        },
        {"args": [[]], "expected": 0, "name": "empty array"},
        {"args": [[1]], "expected": 1, "name": "single element"},
        {"args": [[1, 2, 3]], "expected": 3, "name": "no duplicates"},
        {"args": [[1, 1, 1, 1, 1]], "expected": 1, "name": "all duplicates"},
    ],
    "minimum_window_substring": [
        {"args": ["ADOBECODEBANC", "ABC"], "expected": "BANC", "name": "basic case"},
        {"args": ["a", "a"], "expected": "a", "name": "single char match"},
        {"args": ["a", "aa"], "expected": "", "name": "impossible"},
        {"args": ["aa", "aa"], "expected": "aa", "name": "exact match"},
        {"args": ["", "a"], "expected": "", "name": "empty s"},
        {"args": ["abc", ""], "expected": "", "name": "empty t"},
        {"args": ["aaab", "aab"], "expected": "aab", "name": "repeated chars in t"},
    ],
    "sort_colors": [
        {
            "args": [[2, 0, 2, 1, 1, 0]],
            "expected": [0, 0, 1, 1, 2, 2],
            "name": "basic case",
        },
        {"args": [[2, 0, 1]], "expected": [0, 1, 2], "name": "one of each"},
        {"args": [[0]], "expected": [0], "name": "single element"},
        {"args": [[1, 1, 1]], "expected": [1, 1, 1], "name": "all same"},
        {
            "args": [[2, 2, 2, 1, 1, 0, 0]],
            "expected": [0, 0, 1, 1, 2, 2, 2],
            "name": "reverse sorted",
        },
        {"args": [[]], "expected": [], "name": "empty array"},
    ],
    "trapping_rain_water": [
        {
            "args": [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]],
            "expected": 6,
            "name": "basic case",
        },
        {"args": [[4, 2, 0, 3, 2, 5]], "expected": 9, "name": "another case"},
        {"args": [[4, 2, 3]], "expected": 1, "name": "simple trap"},
        {"args": [[1, 2, 3, 4, 5]], "expected": 0, "name": "increasing"},
        {"args": [[5, 4, 3, 2, 1]], "expected": 0, "name": "decreasing"},
        {"args": [[]], "expected": 0, "name": "empty array"},
        {"args": [[5]], "expected": 0, "name": "single element"},
        {"args": [[1, 2]], "expected": 0, "name": "two elements"},
    ],
    "find_all_anagrams": [
        {"args": ["cbaebabacd", "abc"], "expected": [0, 6], "name": "basic case"},
        {"args": ["abab", "ab"], "expected": [0, 1, 2], "name": "overlapping"},
        {"args": ["abc", "def"], "expected": [], "name": "no anagrams"},
        {"args": ["a", "a"], "expected": [0], "name": "single char"},
        {"args": ["", "abc"], "expected": [], "name": "empty string s"},
        {"args": ["abc", ""], "expected": [], "name": "empty pattern p"},
    ],
    "longest_repeating_character_replacement": [
        {"args": ["ABAB", 2], "expected": 4, "name": "basic case"},
        {"args": ["AABABBA", 1], "expected": 4, "name": "with limit 1"},
        {"args": ["AAAA", 0], "expected": 4, "name": "all same"},
        {"args": ["ABCD", 2], "expected": 3, "name": "all different"},
        {"args": ["", 2], "expected": 0, "name": "empty string"},
        {"args": ["A", 0], "expected": 1, "name": "single char"},
    ],
    "permutation_in_string": [
        {"args": ["ab", "eidbaooo"], "expected": True, "name": "contains permutation"},
        {"args": ["ab", "eidboaoo"], "expected": False, "name": "no permutation"},
        {"args": ["a", "a"], "expected": True, "name": "single char"},
        {"args": ["abc", "bca"], "expected": True, "name": "exact anagram"},
        {"args": ["", "abc"], "expected": True, "name": "empty s1"},
        {"args": ["abc", ""], "expected": False, "name": "empty s2"},
    ],
    "max_consecutive_ones_iii": [
        {
            "args": [[1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0], 2],
            "expected": 6,
            "name": "basic case",
        },
        {
            "args": [[0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1], 3],
            "expected": 10,
            "name": "longer",
        },
        {"args": [[1, 1, 1], 0], "expected": 3, "name": "all ones no flips"},
        {"args": [[0, 0, 0], 3], "expected": 3, "name": "all zeros flip all"},
        {"args": [[], 0], "expected": 0, "name": "empty array"},
        {"args": [[1], 0], "expected": 1, "name": "single one"},
        {"args": [[0], 1], "expected": 1, "name": "single zero flip it"},
    ],
    "boats_to_save_people": [
        {"args": [[1, 2], 3], "expected": 1, "name": "fit together"},
        {"args": [[3, 2, 2, 1], 3], "expected": 3, "name": "basic case"},
        {"args": [[3, 5, 3, 4], 5], "expected": 4, "name": "one each"},
        {"args": [[1, 1, 1, 1], 2], "expected": 2, "name": "pairs"},
        {"args": [[3], 5], "expected": 1, "name": "single person"},
    ],
    "four_sum": [
        {
            "args": [[1, 0, -1, 0, -2, 2], 0],
            "expected": [[-2, -1, 1, 2], [-2, 0, 0, 2], [-1, 0, 0, 1]],
            "name": "basic case",
            "compare": "set_of_tuples",
        },
        {
            "args": [[2, 2, 2, 2, 2], 8],
            "expected": [[2, 2, 2, 2]],
            "name": "all same",
            "compare": "set_of_tuples",
        },
        {
            "args": [[0, 0, 0, 0], 0],
            "expected": [[0, 0, 0, 0]],
            "name": "all zeros",
            "compare": "set_of_tuples",
        },
    ],
    "is_palindrome_ii": [
        {"args": ["aba"], "expected": True, "name": "already palindrome"},
        {"args": ["abca"], "expected": True, "name": "remove one char"},
        {"args": ["abc"], "expected": False, "name": "cannot form"},
        {"args": ["deeee"], "expected": True, "name": "remove first"},
    ],
    "reverse_words": [
        {
            "args": ["the sky is blue"],
            "expected": "blue is sky the",
            "name": "basic case",
        },
        {
            "args": ["  hello world  "],
            "expected": "world hello",
            "name": "extra spaces",
        },
        {
            "args": ["a good   example"],
            "expected": "example good a",
            "name": "multiple spaces",
        },
    ],
    "remove_duplicates_ii": [
        {"args": [[1, 1, 1, 2, 2, 3]], "expected": 5, "name": "basic case"},
        {
            "args": [[0, 0, 1, 1, 1, 1, 2, 3, 3]],
            "expected": 7,
            "name": "more duplicates",
        },
        {"args": [[1, 2, 3]], "expected": 3, "name": "no duplicates"},
    ],
    "string_compression": [
        {
            "args": [["a", "a", "b", "b", "c", "c", "c"]],
            "expected": 6,
            "name": "basic case",
        },
        {"args": [["a"]], "expected": 1, "name": "single char"},
        {"args": [["a", "b", "c"]], "expected": 3, "name": "no compression"},
        {
            "args": [["a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a", "a"]],
            "expected": 3,
            "name": "twelve a's",
        },
    ],
    "longest_mountain": [
        {"args": [[2, 1, 4, 7, 3, 2, 5]], "expected": 5, "name": "basic case"},
        {"args": [[2, 2, 2]], "expected": 0, "name": "all same"},
        {
            "args": [[0, 1, 2, 3, 4, 5, 4, 3, 2, 1, 0]],
            "expected": 11,
            "name": "full mountain",
        },
        {"args": [[]], "expected": 0, "name": "empty array"},
        {"args": [[1]], "expected": 0, "name": "single element"},
        {"args": [[1, 2]], "expected": 0, "name": "two elements"},
    ],
}
