"""
Topic 02: Arrays & Strings
"""

from ..types import TestCasesDict

TOPIC_02_TESTS: TestCasesDict = {
    "two_sum": [
        {"args": [[2, 7, 11, 15], 9], "expected": [0, 1], "name": "basic case"},
        {"args": [[3, 2, 4], 6], "expected": [1, 2], "name": "middle elements"},
        {"args": [[3, 3], 6], "expected": [0, 1], "name": "duplicate values"},
        {"args": [[1, 2, 3, 4, 5], 9], "expected": [3, 4], "name": "end elements"},
        {
            "args": [[-1, -2, -3, -4, -5], -8],
            "expected": [2, 4],
            "name": "negative numbers",
        },
        {"args": [[0, 4, 3, 0], 0], "expected": [0, 3], "name": "zero target"},
    ],
    "best_time_to_buy_sell": [
        {"args": [[7, 1, 5, 3, 6, 4]], "expected": 5, "name": "basic profit"},
        {"args": [[7, 6, 4, 3, 1]], "expected": 0, "name": "decreasing prices"},
        {"args": [[1, 2]], "expected": 1, "name": "two elements profit"},
        {"args": [[2, 1]], "expected": 0, "name": "two elements no profit"},
        {"args": [[1]], "expected": 0, "name": "single element"},
        {"args": [[3, 3, 3, 3]], "expected": 0, "name": "all same price"},
        {"args": [[1, 2, 3, 4, 5]], "expected": 4, "name": "increasing prices"},
        {"args": [[2, 4, 1, 7]], "expected": 6, "name": "buy after first sell point"},
    ],
    "contains_duplicate": [
        {"args": [[1, 2, 3, 1]], "expected": True, "name": "has duplicate"},
        {"args": [[1, 2, 3, 4]], "expected": False, "name": "no duplicate"},
        {"args": [[]], "expected": False, "name": "empty array"},
        {"args": [[1]], "expected": False, "name": "single element"},
        {"args": [[1, 1]], "expected": True, "name": "two same elements"},
        {
            "args": [[1, 2, 3, 4, 5, 6, 7, 8, 9, 1]],
            "expected": True,
            "name": "duplicate at end",
        },
    ],
    "max_subarray": [
        {
            "args": [[-2, 1, -3, 4, -1, 2, 1, -5, 4]],
            "expected": 6,
            "name": "basic kadane",
        },
        {"args": [[1]], "expected": 1, "name": "single element"},
        {"args": [[5, 4, -1, 7, 8]], "expected": 23, "name": "almost all positive"},
        {"args": [[-1]], "expected": -1, "name": "single negative"},
        {"args": [[-2, -1]], "expected": -1, "name": "all negative"},
        {"args": [[1, 2, 3, 4, 5]], "expected": 15, "name": "all positive"},
        {
            "args": [[-1, -2, -3, -4, -5]],
            "expected": -1,
            "name": "all negative pick max",
        },
    ],
    "rotate_array": [
        {
            "args": [[1, 2, 3, 4, 5, 6, 7], 3],
            "expected": [5, 6, 7, 1, 2, 3, 4],
            "name": "rotate by 3",
        },
        {
            "args": [[-1, -100, 3, 99], 2],
            "expected": [3, 99, -1, -100],
            "name": "negative numbers",
        },
        {"args": [[1, 2], 1], "expected": [2, 1], "name": "rotate by 1"},
        {"args": [[1, 2, 3], 3], "expected": [1, 2, 3], "name": "rotate by length"},
        {
            "args": [[1, 2, 3], 4],
            "expected": [3, 1, 2],
            "name": "rotate more than length",
        },
        {"args": [[1], 5], "expected": [1], "name": "single element"},
        {"args": [[1, 2, 3], 0], "expected": [1, 2, 3], "name": "rotate by 0"},
        {"args": [[], 3], "expected": [], "name": "empty array"},
    ],
    "reverse_string": [
        {"args": ["hello"], "expected": "olleh", "name": "hello"},
        {"args": ["Hannah"], "expected": "hannaH", "name": "Hannah"},
        {"args": ["a"], "expected": "a", "name": "single char"},
        {"args": ["ab"], "expected": "ba", "name": "two chars"},
        {"args": ["abcd"], "expected": "dcba", "name": "four chars"},
        {"args": [""], "expected": "", "name": "empty string"},
    ],
    "valid_anagram": [
        {"args": ["anagram", "nagaram"], "expected": True, "name": "valid anagram"},
        {"args": ["rat", "car"], "expected": False, "name": "not anagram"},
        {"args": ["", ""], "expected": True, "name": "empty strings"},
        {"args": ["a", "a"], "expected": True, "name": "single char same"},
        {"args": ["a", "b"], "expected": False, "name": "single char different"},
        {"args": ["listen", "silent"], "expected": True, "name": "listen silent"},
        {"args": ["hello", "world"], "expected": False, "name": "different words"},
        {"args": ["aab", "aba"], "expected": True, "name": "repeated chars"},
    ],
    "longest_common_prefix": [
        {
            "args": [["flower", "flow", "flight"]],
            "expected": "fl",
            "name": "basic prefix",
        },
        {
            "args": [["dog", "racecar", "car"]],
            "expected": "",
            "name": "no common prefix",
        },
        {"args": [[]], "expected": "", "name": "empty array"},
        {"args": [["single"]], "expected": "single", "name": "single word"},
        {"args": [["", "b"]], "expected": "", "name": "empty string in array"},
        {"args": [["abc", "abc", "abc"]], "expected": "abc", "name": "all same"},
        {"args": [["ab", "a"]], "expected": "a", "name": "one is prefix of other"},
    ],
    "product_except_self": [
        {"args": [[1, 2, 3, 4]], "expected": [24, 12, 8, 6], "name": "basic case"},
        {"args": [[-1, 1, 0, -3, 3]], "expected": [0, 0, 9, 0, 0], "name": "with zero"},
        {"args": [[1, 2]], "expected": [2, 1], "name": "two elements"},
        {"args": [[0, 0]], "expected": [0, 0], "name": "two zeros"},
        {"args": [[1, 1, 1, 1]], "expected": [1, 1, 1, 1], "name": "all ones"},
        {"args": [[2, 3, 4, 5]], "expected": [60, 40, 30, 24], "name": "no zeros"},
    ],
    "string_to_integer": [
        {"args": ["42"], "expected": 42, "name": "positive number"},
        {"args": ["   -42"], "expected": -42, "name": "negative with spaces"},
        {"args": ["4193 with words"], "expected": 4193, "name": "number with words"},
        {"args": ["words and 987"], "expected": 0, "name": "words first"},
        {"args": [""], "expected": 0, "name": "empty string"},
        {"args": ["   "], "expected": 0, "name": "only spaces"},
        {"args": ["-91283472332"], "expected": -2147483648, "name": "underflow"},
        {"args": ["91283472332"], "expected": 2147483647, "name": "overflow"},
        {"args": ["+1"], "expected": 1, "name": "positive sign"},
        {"args": ["+-12"], "expected": 0, "name": "invalid signs"},
    ],
    "move_zeroes": [
        {
            "args": [[0, 1, 0, 3, 12]],
            "expected": [1, 3, 12, 0, 0],
            "name": "basic case",
        },
        {"args": [[0]], "expected": [0], "name": "single zero"},
        {"args": [[1, 2, 3]], "expected": [1, 2, 3], "name": "no zeros"},
        {"args": [[0, 0, 0]], "expected": [0, 0, 0], "name": "all zeros"},
        {"args": [[1, 0]], "expected": [1, 0], "name": "two elements"},
    ],
    "spiral_matrix": [
        {
            "args": [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]],
            "expected": [1, 2, 3, 6, 9, 8, 7, 4, 5],
            "name": "3x3 matrix",
        },
        {
            "args": [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]],
            "expected": [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7],
            "name": "3x4 matrix",
        },
        {"args": [[[1]]], "expected": [1], "name": "single element"},
        {"args": [[[1, 2], [3, 4]]], "expected": [1, 2, 4, 3], "name": "2x2 matrix"},
    ],
    "set_matrix_zeroes": [
        {
            "args": [[[1, 1, 1], [1, 0, 1], [1, 1, 1]]],
            "expected": [[1, 0, 1], [0, 0, 0], [1, 0, 1]],
            "name": "center zero",
        },
        {
            "args": [[[0, 1, 2, 0], [3, 4, 5, 2], [1, 3, 1, 5]]],
            "expected": [[0, 0, 0, 0], [0, 4, 5, 0], [0, 3, 1, 0]],
            "name": "corner zeros",
        },
        {"args": [[[1, 2], [3, 4]]], "expected": [[1, 2], [3, 4]], "name": "no zeros"},
    ],
    "find_all_duplicates": [
        {
            "args": [[4, 3, 2, 7, 8, 2, 3, 1]],
            "expected": [2, 3],
            "name": "basic case",
            "compare": "set",
        },
        {"args": [[1, 1, 2]], "expected": [1], "name": "single duplicate"},
        {"args": [[1, 2, 3, 4]], "expected": [], "name": "no duplicates"},
        {"args": [[1, 1]], "expected": [1], "name": "two elements same"},
    ],
    "first_missing_positive": [
        {"args": [[1, 2, 0]], "expected": 3, "name": "basic case"},
        {"args": [[3, 4, -1, 1]], "expected": 2, "name": "with negatives"},
        {"args": [[7, 8, 9, 11, 12]], "expected": 1, "name": "missing 1"},
        {"args": [[1, 2, 3]], "expected": 4, "name": "consecutive"},
        {"args": [[1]], "expected": 2, "name": "single element"},
    ],
    "roman_to_integer": [
        {"args": ["III"], "expected": 3, "name": "simple"},
        {"args": ["LVIII"], "expected": 58, "name": "medium"},
        {"args": ["MCMXCIV"], "expected": 1994, "name": "complex"},
        {"args": ["IV"], "expected": 4, "name": "subtraction"},
        {"args": ["IX"], "expected": 9, "name": "nine"},
    ],
    "integer_to_roman": [
        {"args": [3], "expected": "III", "name": "simple"},
        {"args": [58], "expected": "LVIII", "name": "medium"},
        {"args": [1994], "expected": "MCMXCIV", "name": "complex"},
        {"args": [4], "expected": "IV", "name": "four"},
        {"args": [9], "expected": "IX", "name": "nine"},
    ],
    "is_palindrome_number": [
        {"args": [121], "expected": True, "name": "palindrome"},
        {"args": [-121], "expected": False, "name": "negative"},
        {"args": [10], "expected": False, "name": "ends in zero"},
        {"args": [0], "expected": True, "name": "zero"},
        {"args": [12321], "expected": True, "name": "five digits"},
    ],
    "plus_one": [
        {"args": [[1, 2, 3]], "expected": [1, 2, 4], "name": "basic case"},
        {"args": [[9]], "expected": [1, 0], "name": "single nine"},
        {"args": [[9, 9, 9]], "expected": [1, 0, 0, 0], "name": "all nines"},
        {"args": [[0]], "expected": [1], "name": "zero"},
        {"args": [[1, 9, 9]], "expected": [2, 0, 0], "name": "carry over"},
    ],
    "merge_sorted_array": [
        {
            "args": [[1, 2, 3, 0, 0, 0], 3, [2, 5, 6], 3],
            "expected": [1, 2, 2, 3, 5, 6],
            "name": "basic case",
        },
        {"args": [[1], 1, [], 0], "expected": [1], "name": "empty second"},
        {"args": [[0], 0, [1], 1], "expected": [1], "name": "empty first"},
        {
            "args": [[4, 5, 6, 0, 0, 0], 3, [1, 2, 3], 3],
            "expected": [1, 2, 3, 4, 5, 6],
            "name": "second smaller",
        },
    ],
    "majority_element": [
        {"args": [[3, 2, 3]], "expected": 3, "name": "basic case"},
        {"args": [[2, 2, 1, 1, 1, 2, 2]], "expected": 2, "name": "longer"},
        {"args": [[1]], "expected": 1, "name": "single element"},
        {"args": [[1, 1]], "expected": 1, "name": "two same"},
    ],
    "find_disappeared_numbers": [
        {"args": [[4, 3, 2, 7, 8, 2, 3, 1]], "expected": [5, 6], "name": "basic case"},
        {"args": [[1, 1]], "expected": [2], "name": "duplicate"},
        {"args": [[1, 2, 3]], "expected": [], "name": "all present"},
        {"args": [[2, 2]], "expected": [1], "name": "missing one"},
    ],
    "single_number": [
        {"args": [[2, 2, 1]], "expected": 1, "name": "basic case"},
        {"args": [[4, 1, 2, 1, 2]], "expected": 4, "name": "longer"},
        {"args": [[1]], "expected": 1, "name": "single element"},
        {"args": [[-1, -1, -2]], "expected": -2, "name": "negatives"},
    ],
    "is_subsequence": [
        {"args": ["abc", "ahbgdc"], "expected": True, "name": "is subsequence"},
        {"args": ["axc", "ahbgdc"], "expected": False, "name": "not subsequence"},
        {"args": ["", "abc"], "expected": True, "name": "empty s"},
        {"args": ["abc", ""], "expected": False, "name": "empty t"},
        {"args": ["b", "abc"], "expected": True, "name": "single char"},
    ],
    "length_of_last_word": [
        {"args": ["Hello World"], "expected": 5, "name": "basic case"},
        {"args": ["   fly me   to   the moon  "], "expected": 4, "name": "with spaces"},
        {"args": ["luffy is still joyboy"], "expected": 6, "name": "no trailing space"},
        {"args": ["a"], "expected": 1, "name": "single char"},
    ],
    "search_insert_position": [
        {"args": [[1, 3, 5, 6], 5], "expected": 2, "name": "found"},
        {"args": [[1, 3, 5, 6], 2], "expected": 1, "name": "insert middle"},
        {"args": [[1, 3, 5, 6], 7], "expected": 4, "name": "insert end"},
        {"args": [[1, 3, 5, 6], 0], "expected": 0, "name": "insert start"},
    ],
    "pascal_triangle": [
        {
            "args": [5],
            "expected": [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]],
            "name": "five rows",
        },
        {"args": [1], "expected": [[1]], "name": "single row"},
        {"args": [2], "expected": [[1], [1, 1]], "name": "two rows"},
    ],
    "pascal_triangle_row": [
        {"args": [3], "expected": [1, 3, 3, 1], "name": "row 3"},
        {"args": [0], "expected": [1], "name": "row 0"},
        {"args": [1], "expected": [1, 1], "name": "row 1"},
        {"args": [4], "expected": [1, 4, 6, 4, 1], "name": "row 4"},
    ],
}
