"""
Topic 05: Linked Lists
"""

from ..types import TestCasesDict

TOPIC_05_TESTS: TestCasesDict = {
    "reverse_list": [
        {
            "args": [[1, 2, 3, 4, 5]],
            "expected": [5, 4, 3, 2, 1],
            "name": "standard list",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2]],
            "expected": [2, 1],
            "name": "two nodes",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1]],
            "expected": [1],
            "name": "single node",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[]],
            "expected": [],
            "name": "empty list",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "merge_two_lists": [
        {
            "args": [[1, 2, 4], [1, 3, 4]],
            "expected": [1, 1, 2, 3, 4, 4],
            "name": "standard merge",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[], []],
            "expected": [],
            "name": "both empty",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[], [0]],
            "expected": [0],
            "name": "first empty",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1], [2]],
            "expected": [1, 2],
            "name": "single nodes",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 3, 5], [2, 4, 6]],
            "expected": [1, 2, 3, 4, 5, 6],
            "name": "interleaved",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2, 3], []],
            "expected": [1, 2, 3],
            "name": "second empty",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
    ],
    "has_cycle": [
        {
            "args": [[3, 2, 0, -4], 1],
            "expected": True,
            "name": "cycle at pos 1",
            "input_type": "linked_list_cycle",
        },
        {
            "args": [[1, 2], 0],
            "expected": True,
            "name": "cycle at head",
            "input_type": "linked_list_cycle",
        },
        {
            "args": [[1, 2, 3], 2],
            "expected": True,
            "name": "cycle at tail",
            "input_type": "linked_list_cycle",
        },
        {
            "args": [[1], -1],
            "expected": False,
            "name": "single no cycle",
            "input_type": "linked_list_cycle",
        },
        {
            "args": [[1, 2, 3], -1],
            "expected": False,
            "name": "no cycle",
            "input_type": "linked_list_cycle",
        },
        {
            "args": [[], -1],
            "expected": False,
            "name": "empty list",
            "input_type": "linked_list_cycle",
        },
    ],
    "remove_nth_from_end": [
        {
            "args": [[1, 2, 3, 4, 5], 2],
            "expected": [1, 2, 3, 5],
            "name": "remove 2nd from end",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1], 1],
            "expected": [],
            "name": "remove only node",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2], 1],
            "expected": [1],
            "name": "remove last",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2], 2],
            "expected": [2],
            "name": "remove first",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "find_middle": [
        {
            "args": [[1, 2, 3, 4, 5]],
            "expected": 3,
            "name": "odd length",
            "input_type": "linked_list",
            "output_type": "node_val",
        },
        {
            "args": [[1, 2, 3, 4, 5, 6]],
            "expected": 4,
            "name": "even length (second middle)",
            "input_type": "linked_list",
            "output_type": "node_val",
        },
        {
            "args": [[1]],
            "expected": 1,
            "name": "single node",
            "input_type": "linked_list",
            "output_type": "node_val",
        },
        {
            "args": [[1, 2]],
            "expected": 2,
            "name": "two nodes",
            "input_type": "linked_list",
            "output_type": "node_val",
        },
        {
            "args": [[1, 2, 3]],
            "expected": 2,
            "name": "three nodes",
            "input_type": "linked_list",
            "output_type": "node_val",
        },
    ],
    "is_palindrome_list": [
        {
            "args": [[1, 2, 2, 1]],
            "expected": True,
            "name": "even palindrome",
            "input_type": "linked_list",
        },
        {
            "args": [[1, 2, 3, 2, 1]],
            "expected": True,
            "name": "odd palindrome",
            "input_type": "linked_list",
        },
        {
            "args": [[1, 2]],
            "expected": False,
            "name": "not palindrome",
            "input_type": "linked_list",
        },
        {
            "args": [[1]],
            "expected": True,
            "name": "single node",
            "input_type": "linked_list",
        },
        {
            "args": [[]],
            "expected": True,
            "name": "empty list",
            "input_type": "linked_list",
        },
    ],
    "add_two_numbers": [
        {
            "args": [[2, 4, 3], [5, 6, 4]],
            "expected": [7, 0, 8],
            "name": "342 + 465 = 807",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[0], [0]],
            "expected": [0],
            "name": "0 + 0",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[9, 9, 9], [1]],
            "expected": [0, 0, 0, 1],
            "name": "999 + 1 = 1000",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2, 3], [4, 5, 6]],
            "expected": [5, 7, 9],
            "name": "321 + 654 = 975",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[5], [5]],
            "expected": [0, 1],
            "name": "5 + 5 = 10 (carry)",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 8], [0]],
            "expected": [1, 8],
            "name": "different lengths",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[], [1, 2]],
            "expected": [1, 2],
            "name": "first list empty",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2], []],
            "expected": [1, 2],
            "name": "second list empty",
            "input_type": "linked_lists",
            "output_type": "linked_list_to_list",
        },
    ],
    "reorder_list": [
        {
            "args": [[1, 2, 3, 4]],
            "expected": [1, 4, 2, 3],
            "name": "even length",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2, 3, 4, 5]],
            "expected": [1, 5, 2, 4, 3],
            "name": "odd length",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1]],
            "expected": [1],
            "name": "single node",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2]],
            "expected": [1, 2],
            "name": "two nodes",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2, 3]],
            "expected": [1, 3, 2],
            "name": "three nodes",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[]],
            "expected": [],
            "name": "empty list",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "swap_pairs": [
        {
            "args": [[1, 2, 3, 4]],
            "expected": [2, 1, 4, 3],
            "name": "even length",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2, 3]],
            "expected": [2, 1, 3],
            "name": "odd length",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1]],
            "expected": [1],
            "name": "single node",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[]],
            "expected": [],
            "name": "empty list",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "rotate_list": [
        {
            "args": [[1, 2, 3, 4, 5], 2],
            "expected": [4, 5, 1, 2, 3],
            "name": "rotate by 2",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[0, 1, 2], 4],
            "expected": [2, 0, 1],
            "name": "rotate more than length",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1], 1],
            "expected": [1],
            "name": "single node",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[], 0],
            "expected": [],
            "name": "empty list",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "delete_duplicates": [
        {
            "args": [[1, 1, 2]],
            "expected": [1, 2],
            "name": "basic case",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 1, 2, 3, 3]],
            "expected": [1, 2, 3],
            "name": "multiple duplicates",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 1, 1]],
            "expected": [1],
            "name": "all same",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2, 3]],
            "expected": [1, 2, 3],
            "name": "no duplicates",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "delete_duplicates_ii": [
        {
            "args": [[1, 2, 3, 3, 4, 4, 5]],
            "expected": [1, 2, 5],
            "name": "basic case",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 1, 1, 2, 3]],
            "expected": [2, 3],
            "name": "start with duplicates",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 1]],
            "expected": [],
            "name": "all duplicates",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "partition_list": [
        {
            "args": [[1, 4, 3, 2, 5, 2], 3],
            "expected": [1, 2, 2, 4, 3, 5],
            "name": "basic case",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[2, 1], 2],
            "expected": [1, 2],
            "name": "two nodes",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1], 0],
            "expected": [1],
            "name": "single node",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "sort_list": [
        {
            "args": [[4, 2, 1, 3]],
            "expected": [1, 2, 3, 4],
            "name": "basic case",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[-1, 5, 3, 4, 0]],
            "expected": [-1, 0, 3, 4, 5],
            "name": "with negatives",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[]],
            "expected": [],
            "name": "empty list",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1]],
            "expected": [1],
            "name": "single node",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "odd_even_list": [
        {
            "args": [[1, 2, 3, 4, 5]],
            "expected": [1, 3, 5, 2, 4],
            "name": "odd length",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[2, 1, 3, 5, 6, 4, 7]],
            "expected": [2, 3, 6, 7, 1, 5, 4],
            "name": "longer",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2]],
            "expected": [1, 2],
            "name": "two nodes",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1]],
            "expected": [1],
            "name": "single node",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "reverse_between": [
        {
            "args": [[1, 2, 3, 4, 5], 2, 4],
            "expected": [1, 4, 3, 2, 5],
            "name": "middle section",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[5], 1, 1],
            "expected": [5],
            "name": "single node",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2, 3], 1, 3],
            "expected": [3, 2, 1],
            "name": "entire list",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "insert_into_sorted": [
        {
            "args": [[1, 3, 4], 2],
            "expected": [1, 2, 3, 4],
            "name": "insert middle",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[1, 2, 3], 4],
            "expected": [1, 2, 3, 4],
            "name": "insert end",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[2, 3, 4], 1],
            "expected": [1, 2, 3, 4],
            "name": "insert start",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
        {
            "args": [[], 1],
            "expected": [1],
            "name": "empty list",
            "input_type": "linked_list",
            "output_type": "linked_list_to_list",
        },
    ],
    "split_list": [
        {
            "args": [[1, 2, 3], 5],
            "expected": [[1], [2], [3], [], []],
            "name": "more parts than nodes",
            "input_type": "linked_list",
        },
        {
            "args": [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 3],
            "expected": [[1, 2, 3, 4], [5, 6, 7], [8, 9, 10]],
            "name": "even split",
            "input_type": "linked_list",
        },
    ],
    "linked_list_components": [
        {
            "args": [[0, 1, 2, 3], [0, 1, 3]],
            "expected": 2,
            "name": "basic case",
            "input_type": "linked_list",
        },
        {
            "args": [[0, 1, 2, 3, 4], [0, 3, 1, 4]],
            "expected": 2,
            "name": "scattered",
            "input_type": "linked_list",
        },
        {
            "args": [[0, 1, 2], [0, 1, 2]],
            "expected": 1,
            "name": "all connected",
            "input_type": "linked_list",
        },
    ],
}
