"""
Topic 02: Arrays & Strings
"""

TOPIC_02_TESTS = {
    "two_sum": [
        {"args": [[2, 7, 11, 15], 9], "expected": [0, 1], "name": "basic case"},
        {"args": [[3, 2, 4], 6], "expected": [1, 2], "name": "middle elements"},
        {"args": [[3, 3], 6], "expected": [0, 1], "name": "duplicate values"},
        {"args": [[1, 2, 3, 4, 5], 9], "expected": [3, 4], "name": "end elements"},
        {"args": [[-1, -2, -3, -4, -5], -8], "expected": [2, 4], "name": "negative numbers"},
        {"args": [[0, 4, 3, 0], 0], "expected": [0, 3], "name": "zero target"},
    ],
    "best_time_to_buy_sell": [
        {"args": [[7, 1, 5, 3, 6, 4]], "expected": 5, "name": "basic profit"},
        {"args": [[7, 6, 4, 3, 1]], "expected": 0, "name": "decreasing prices"},
        {"args": [[1, 2]], "expected": 1, "name": "two elements profit"},
        {"args": [[2, 1]], "expected": 0, "name": "two elements no profit"},
        {"args": [[1]], "expected": 0, "name": "single element"},
        {"args": [[3, 3, 3, 3]], "expected": 0, "name": "all same price"},
        {"args": [[1, 2, 3, 4, 5]], "expected": 4, "name": "increasing prices"},
        {"args": [[2, 4, 1, 7]], "expected": 6, "name": "buy after first sell point"},
    ],
    "contains_duplicate": [
        {"args": [[1, 2, 3, 1]], "expected": True, "name": "has duplicate"},
        {"args": [[1, 2, 3, 4]], "expected": False, "name": "no duplicate"},
        {"args": [[]], "expected": False, "name": "empty array"},
        {"args": [[1]], "expected": False, "name": "single element"},
        {"args": [[1, 1]], "expected": True, "name": "two same elements"},
        {"args": [[1, 2, 3, 4, 5, 6, 7, 8, 9, 1]], "expected": True, "name": "duplicate at end"},
    ],
    "max_subarray": [
        {"args": [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], "expected": 6, "name": "basic kadane"},
        {"args": [[1]], "expected": 1, "name": "single element"},
        {"args": [[5, 4, -1, 7, 8]], "expected": 23, "name": "almost all positive"},
        {"args": [[-1]], "expected": -1, "name": "single negative"},
        {"args": [[-2, -1]], "expected": -1, "name": "all negative"},
        {"args": [[1, 2, 3, 4, 5]], "expected": 15, "name": "all positive"},
        {"args": [[-1, -2, -3, -4, -5]], "expected": -1, "name": "all negative pick max"},
    ],
    "rotate_array": [
        {"args": [[1, 2, 3, 4, 5, 6, 7], 3], "expected": [5, 6, 7, 1, 2, 3, 4], "name": "rotate by 3"},
        {"args": [[-1, -100, 3, 99], 2], "expected": [3, 99, -1, -100], "name": "negative numbers"},
        {"args": [[1, 2], 1], "expected": [2, 1], "name": "rotate by 1"},
        {"args": [[1, 2, 3], 3], "expected": [1, 2, 3], "name": "rotate by length"},
        {"args": [[1, 2, 3], 4], "expected": [3, 1, 2], "name": "rotate more than length"},
        {"args": [[1], 5], "expected": [1], "name": "single element"},
    ],
    "reverse_string": [
        {"args": [["h", "e", "l", "l", "o"]], "expected": ["o", "l", "l", "e", "h"], "name": "hello"},
        {"args": [["H", "a", "n", "n", "a", "h"]], "expected": ["h", "a", "n", "n", "a", "H"], "name": "Hannah"},
        {"args": [["a"]], "expected": ["a"], "name": "single char"},
        {"args": [["a", "b"]], "expected": ["b", "a"], "name": "two chars"},
        {"args": [["a", "b", "c", "d"]], "expected": ["d", "c", "b", "a"], "name": "four chars"},
    ],
    "valid_anagram": [
        {"args": ["anagram", "nagaram"], "expected": True, "name": "valid anagram"},
        {"args": ["rat", "car"], "expected": False, "name": "not anagram"},
        {"args": ["", ""], "expected": True, "name": "empty strings"},
        {"args": ["a", "a"], "expected": True, "name": "single char same"},
        {"args": ["a", "b"], "expected": False, "name": "single char different"},
        {"args": ["listen", "silent"], "expected": True, "name": "listen silent"},
        {"args": ["hello", "world"], "expected": False, "name": "different words"},
        {"args": ["aab", "aba"], "expected": True, "name": "repeated chars"},
    ],
    "longest_common_prefix": [
        {"args": [["flower", "flow", "flight"]], "expected": "fl", "name": "basic prefix"},
        {"args": [["dog", "racecar", "car"]], "expected": "", "name": "no common prefix"},
        {"args": [[]], "expected": "", "name": "empty array"},
        {"args": [["single"]], "expected": "single", "name": "single word"},
        {"args": [["", "b"]], "expected": "", "name": "empty string in array"},
        {"args": [["abc", "abc", "abc"]], "expected": "abc", "name": "all same"},
        {"args": [["ab", "a"]], "expected": "a", "name": "one is prefix of other"},
    ],
    "product_except_self": [
        {"args": [[1, 2, 3, 4]], "expected": [24, 12, 8, 6], "name": "basic case"},
        {"args": [[-1, 1, 0, -3, 3]], "expected": [0, 0, 9, 0, 0], "name": "with zero"},
        {"args": [[1, 2]], "expected": [2, 1], "name": "two elements"},
        {"args": [[0, 0]], "expected": [0, 0], "name": "two zeros"},
        {"args": [[1, 1, 1, 1]], "expected": [1, 1, 1, 1], "name": "all ones"},
        {"args": [[2, 3, 4, 5]], "expected": [60, 40, 30, 24], "name": "no zeros"},
    ],
    "string_to_integer": [
        {"args": ["42"], "expected": 42, "name": "positive number"},
        {"args": ["   -42"], "expected": -42, "name": "negative with spaces"},
        {"args": ["4193 with words"], "expected": 4193, "name": "number with words"},
        {"args": ["words and 987"], "expected": 0, "name": "words first"},
        {"args": [""], "expected": 0, "name": "empty string"},
        {"args": ["   "], "expected": 0, "name": "only spaces"},
    ],
}
